baseURL = 'https://janbabkiewicz.698407.xyz/'
locale = 'pl-PL'
languageCode = 'pl'
title = 'Jan Babkiewicz – CV & Blog'
timeZone = 'Europe/Warsaw'
theme = ''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "IT/OT – CV online i blog techniczny"
  avatar = "/images/avatar.webp"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]